wave: add <time.h> missing header inclusion
When compiling tinycompress with some libc other than glibc
(e.g. musl libc), compilation fails with the following error:

    In file included from wave.c:11:0:
    /path/to/gcc/sysroot/usr/include/sound/asound.h:404:18: error: field 'trigger_tstamp' has incomplete type
      struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
    [...]

According to POSIX, "struct timespec" is defined in <time.h>. See:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html

This patch fixes this build failure by including <time.h> prior
<sound/asound.h>.

Signed-off-by: Julien Olivain <ju.o@free.fr>